name: "Docker hub auth"
description: "authenticates to docker hub"
runs:
  using: "composite"
  steps:
    - run: echo "${{ secrets.user }}" | docker login -u "${{ secrets.accesstoken }}" --password-stdin
