name: "Docker hub auth"
description: "authenticates to docker hub"
runs:
  using: "composite"
  steps:
    - run: echo "${{ secrets.USERNAME }}" | sudo docker login -u "${{ secrets.ACCESSTOKEN }}" --password-stdin
