name: Build Docker Image

on:
  push:
    branches: [ git-test ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: sudo docker build . -t flaskr
        
      - name: Auth with with docker
        run: ./.github/actions/dockerauth/action.yml
