name: Build Docker Image

on:
  push:
    branches: [ git-test ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: sudo docker build . -t flaskr

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: test
        run: echo ${{ secrets.ACCESSTOKEN }}
        
      - name: Auth with with docker
        uses: ./.github/actions/dockerauth
        with:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
